theme:
  name: readthedocs

site_name: RPM-CRN Documentation
repo_url: https://github.com/mdhurst1/Rocky-Profile-Model/tree/JOSS-Paper

nav:
  - Home: 'docs/index.md'
  - About: 'docs/about.md'
  - Issues: 'https://github.com/mdhurst1/Rocky-Profile-Model/issues'
